site_name: ""

theme:
  name: material
  palette:
    scheme: slate
  features: []

nav:
  - Home: index.md
  - Professional: professional/work-history.md
  - Personal: personal/personal.md

extra_css:
  - stylesheets/extra.css
